//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_project_2.LangResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Final_project_2.LangResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actvation.
        /// </summary>
        public static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actived.
        /// </summary>
        public static string Actived {
            get {
                return ResourceManager.GetString("Actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Tours.
        /// </summary>
        public static string ActiveTours {
            get {
                return ResourceManager.GetString("ActiveTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Active Tour.
        /// </summary>
        public static string AddActiveTour {
            get {
                return ResourceManager.GetString("AddActiveTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Item.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Tour Priod.
        /// </summary>
        public static string AddPriod {
            get {
                return ResourceManager.GetString("AddPriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string Adminpnl {
            get {
                return ResourceManager.GetString("Adminpnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have account?.
        /// </summary>
        public static string Alreadyhaveacc {
            get {
                return ResourceManager.GetString("Alreadyhaveacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City and Country.
        /// </summary>
        public static string CityCountry {
            get {
                return ResourceManager.GetString("CityCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Comments.
        /// </summary>
        public static string CommentsList {
            get {
                return ResourceManager.GetString("CommentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePerson.
        /// </summary>
        public static string CreatePerson {
            get {
                return ResourceManager.GetString("CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Tour.
        /// </summary>
        public static string CreateTour {
            get {
                return ResourceManager.GetString("CreateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delet Comment.
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want Delete this Item?.
        /// </summary>
        public static string DeleteItemSure {
            get {
                return ResourceManager.GetString("DeleteItemSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tour.
        /// </summary>
        public static string DeleteTour {
            get {
                return ResourceManager.GetString("DeleteTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tour Priod.
        /// </summary>
        public static string DeleteTourPriod {
            get {
                return ResourceManager.GetString("DeleteTourPriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying a tour is an ideal solution to experience more trips at a reasonable cost. By purchasing travel tours, you can easily receive all the services related to plane tickets, hotel reservations, obtaining visas, transfers and sightseeing plans at your destination. Flytoday has provided you with the possibility of buying a tour to different destinations in the world with the best price and the most complete service.
        ///Flytoday is considered one of the most reliable providers of foreign tours, domestic tours a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string destitle {
            get {
                return ResourceManager.GetString("destitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Person Form.
        /// </summary>
        public static string EditPerson {
            get {
                return ResourceManager.GetString("EditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Vrification.
        /// </summary>
        public static string EmailVerify {
            get {
                return ResourceManager.GetString("EmailVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends At.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorit Food.
        /// </summary>
        public static string FavFood {
            get {
                return ResourceManager.GetString("FavFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorit Sport.
        /// </summary>
        public static string FavSport {
            get {
                return ResourceManager.GetString("FavSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest in Reservation :.
        /// </summary>
        public static string Latest_Reservation {
            get {
                return ResourceManager.GetString("Latest Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest in Comment :.
        /// </summary>
        public static string LatestComment {
            get {
                return ResourceManager.GetString("LatestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest in Person :.
        /// </summary>
        public static string LatestPerson {
            get {
                return ResourceManager.GetString("LatestPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest in Tours :.
        /// </summary>
        public static string LatestTour {
            get {
                return ResourceManager.GetString("LatestTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Tours.
        /// </summary>
        public static string ListOfTours {
            get {
                return ResourceManager.GetString("ListOfTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal User.
        /// </summary>
        public static string NormalUser {
            get {
                return ResourceManager.GetString("NormalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member?.
        /// </summary>
        public static string NotMember {
            get {
                return ResourceManager.GetString("NotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Verified.
        /// </summary>
        public static string NotVerfied {
            get {
                return ResourceManager.GetString("NotVerfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By referring to the Flytoday website or application, fill in the form on the tour page of your desired destination so that our experts will contact you...
        /// </summary>
        public static string ol_destitle1 {
            get {
                return ResourceManager.GetString("ol_destitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the travel tours department directly at 42405000 extension 4..
        /// </summary>
        public static string ol_destitle2 {
            get {
                return ResourceManager.GetString("ol_destitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Users.
        /// </summary>
        public static string PersonList {
            get {
                return ResourceManager.GetString("PersonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumer.
        /// </summary>
        public static string Phonenumer {
            get {
                return ResourceManager.GetString("Phonenumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Comment.
        /// </summary>
        public static string Post_Comment {
            get {
                return ResourceManager.GetString("Post Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Reserve.
        /// </summary>
        public static string RegisterReserve {
            get {
                return ResourceManager.GetString("RegisterReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for Reservation.
        /// </summary>
        public static string ReqReserve {
            get {
                return ResourceManager.GetString("ReqReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved By.
        /// </summary>
        public static string ReservedBy {
            get {
                return ResourceManager.GetString("ReservedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Reservations.
        /// </summary>
        public static string ReserveList {
            get {
                return ResourceManager.GetString("ReserveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Items.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select your desired number.
        /// </summary>
        public static string SelectCount {
            get {
                return ResourceManager.GetString("SelectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing in.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing in to our account.
        /// </summary>
        public static string SigninToacc {
            get {
                return ResourceManager.GetString("SigninToacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat account.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup To Your Account.
        /// </summary>
        public static string SignuptoAcc {
            get {
                return ResourceManager.GetString("SignuptoAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts At.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Limit.
        /// </summary>
        public static string StatLimit {
            get {
                return ResourceManager.GetString("StatLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Adress.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        public static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Tour_Area {
            get {
                return ResourceManager.GetString("Tour Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Tour_Capacity {
            get {
                return ResourceManager.GetString("Tour Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TourDescription {
            get {
                return ResourceManager.GetString("TourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Name.
        /// </summary>
        public static string TourName {
            get {
                return ResourceManager.GetString("TourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for each person.
        /// </summary>
        public static string TourPrice {
            get {
                return ResourceManager.GetString("TourPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Level.
        /// </summary>
        public static string TourQl {
            get {
                return ResourceManager.GetString("TourQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string TourRules {
            get {
                return ResourceManager.GetString("TourRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TourTitle {
            get {
                return ResourceManager.GetString("TourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload FIle.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our Tourism Website.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comment.
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
    }
}
